"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from appConfig import ServidorConfig, DatabaseConfig, CORSConfig

ServidorConfig.configure()
DatabaseConfig.configure()
CORSConfig.configure()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ServidorConfig.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = ServidorConfig.DEBUG

ALLOWED_HOSTS = ServidorConfig.ALLOWED_HOSTS


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'delancert',
    'rest_framework',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

##############################################################
# Base de datos SQLite
##############################################################
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


##############################################################
# Base de datos PostgreSQL
##############################################################
DATABASES = {
    'default': {
        'ENGINE': DatabaseConfig.ENGINE,
        'NAME': DatabaseConfig.NAME,
        'USER': DatabaseConfig.USER,
        'PASSWORD': DatabaseConfig.PASSWORD,
        'HOST': DatabaseConfig.HOST,
        'PORT': DatabaseConfig.PORT,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# =============================================================================
# CORS / CSRF (necesario para frontends separados)
# =============================================================================

CORS_ALLOW_ALL_ORIGINS = CORSConfig.ALLOW_ALL_ORIGINS
CORS_ALLOWED_ORIGINS = CORSConfig.ALLOWED_ORIGINS
CORS_ALLOW_CREDENTIALS = CORSConfig.ALLOW_CREDENTIALS
CSRF_TRUSTED_ORIGINS = CORSConfig.TRUSTED_ORIGINS

# =============================================================================
# Cache (Redis recomendado en producción)
# =============================================================================

REDIS_URL = os.getenv("REDIS_URL", "").strip()
if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
            "KEY_PREFIX": "telemetria",
        }
    }
else:
    # Fallback local (dev)
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "telemetria-locmem",
        }
    }

# =============================================================================
# Celery (Redis recomendado)
# =============================================================================
#
# Filosofía: Celery es opcional. Si REDIS_URL no está configurado, no “rompemos”
# el backend: solo quedará deshabilitado el worker/beat en runtime.
#
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", REDIS_URL).strip() or None
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", REDIS_URL).strip() or None
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = int(os.getenv("CELERY_TASK_TIME_LIMIT", "1800"))  # 30 min
CELERY_TASK_SOFT_TIME_LIMIT = int(os.getenv("CELERY_TASK_SOFT_TIME_LIMIT", "1500"))  # 25 min

# Beat (schedule) opcional: se activa explícitamente por env.
# Importante: si CELERY_BROKER_URL es None, no tiene sentido habilitar beat.
CELERY_ENABLE_BEAT = (os.getenv("CELERY_ENABLE_BEAT", "0") or "0").strip().lower() in ("1", "true", "yes")
if CELERY_ENABLE_BEAT:
    CELERY_BEAT_SCHEDULE = {
        "telemetry-run-every-10m": {
            "task": "telemetria.telemetry_run",
            "schedule": int(os.getenv("CELERY_SCHEDULE_TELEMETRY_RUN_SECONDS", "600")),
            "kwargs": {
                "limit": int(os.getenv("TELEMETRY_RUN_LIMIT", "1000")),
                "batch_size": int(os.getenv("TELEMETRY_RUN_BATCH_SIZE", "1000")),
                "process_timestamps": (os.getenv("TELEMETRY_RUN_PROCESS_TIMESTAMPS", "1") or "1").strip().lower()
                in ("1", "true", "yes"),
                "merge_batch_size": int(os.getenv("TELEMETRY_RUN_MERGE_BATCH_SIZE", "500")),
                "backfill_last_n": int(os.getenv("TELEMETRY_RUN_BACKFILL_LAST_N", "0")),
            },
        },
        "build-aggregates-daily": {
            "task": "telemetria.build_aggregates",
            "schedule": int(os.getenv("CELERY_SCHEDULE_BUILD_AGG_SECONDS", "86400")),
            "kwargs": {"days": int(os.getenv("TELEMETRY_AGG_DAYS", "7"))},
        },
    }

# ============================================================================
# CONFIGURACIÓN DE LOGGING
# ============================================================================

# Crear directorio de logs si no existe
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'detailed': {
            'format': '[{asctime}] {levelname} [{name}] {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'unicode_safe': {
            '()': 'delancert.utils.logging_handlers.UnicodeSafeFilter',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            '()': 'delancert.utils.logging_handlers.SafeConsoleHandler',
            'formatter': 'detailed',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'django.log',
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'detailed',
        },
        'panaccess_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'panaccess.log',
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'detailed',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'errors.log',
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'detailed',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'delancert': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
            'filters': ['unicode_safe'],
        },
        'delancert.server.panaccess_singleton': {
            'handlers': ['console', 'panaccess_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
            'filters': ['unicode_safe'],
        },
        'delancert.utils.auth': {
            'handlers': ['console', 'panaccess_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
            'filters': ['unicode_safe'],
        },
        'delancert.server.panaccess_client': {
            'handlers': ['console', 'panaccess_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
            'filters': ['unicode_safe'],
        },
        'delancert.apps': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
            'filters': ['unicode_safe'],
        },
    },
}