# Generated by Django 6.0.4 on 2026-04-27 16:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delancert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryJobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('run', 'run'), ('sync', 'sync'), ('merge_ott', 'merge_ott'), ('integrity_check', 'integrity_check')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('success', 'success'), ('error', 'error')], db_index=True, max_length=16)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('downloaded', models.IntegerField(blank=True, null=True)),
                ('saved', models.IntegerField(blank=True, null=True)),
                ('skipped', models.IntegerField(blank=True, null=True)),
                ('errors', models.IntegerField(blank=True, null=True)),
                ('highest_record_id_before', models.IntegerField(blank=True, null=True)),
                ('highest_record_id_after', models.IntegerField(blank=True, null=True)),
                ('merged_saved', models.IntegerField(blank=True, null=True)),
                ('merged_deleted_existing', models.IntegerField(blank=True, null=True)),
                ('merge_backfill_last_n', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'telemetry_job_run',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['job_type', 'started_at'], name='telemetry_j_job_typ_c112af_idx'), models.Index(fields=['status', 'started_at'], name='telemetry_j_status_68a422_idx')],
            },
        ),
    ]
