# Generated by Django 6.0.4 on 2026-04-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delancert', '0002_telemetryjobrun'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='telemetryrecordentrydelancer',
            index=models.Index(fields=['actionId', 'recordId'], name='telemetry_r_actionI_41989c_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetryrecordentrydelancer',
            index=models.Index(fields=['subscriberCode', 'dataDate'], name='telemetry_r_subscri_9b7662_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetryrecordentrydelancer',
            index=models.Index(fields=['dataName'], name='telemetry_r_dataNam_2be879_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetryrecordentrydelancer',
            index=models.Index(fields=['dataDate', 'dataName'], name='telemetry_r_dataDat_0379e1_idx'),
        ),
    ]
