# Generated by Django 6.0.4 on 2026-04-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delancert', '0003_telemetryrecordentrydelancer_telemetry_r_actioni_41989c_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryChannelDailyAgg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('channel', models.CharField(db_index=True, max_length=200)),
                ('views', models.IntegerField(default=0)),
                ('unique_users', models.IntegerField(default=0)),
                ('total_duration_seconds', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'telemetry_channel_daily_agg',
                'indexes': [models.Index(fields=['day', 'channel'], name='telemetry_c_day_44d1e4_idx'), models.Index(fields=['channel', 'day'], name='telemetry_c_channel_ec4ebd_idx')],
                'unique_together': {('day', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='TelemetryUserDailyAgg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('subscriber_code', models.CharField(db_index=True, max_length=50)),
                ('views', models.IntegerField(default=0)),
                ('unique_channels', models.IntegerField(default=0)),
                ('total_duration_seconds', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'telemetry_user_daily_agg',
                'indexes': [models.Index(fields=['day', 'subscriber_code'], name='telemetry_u_day_5cdc4e_idx'), models.Index(fields=['subscriber_code', 'day'], name='telemetry_u_subscri_d5763a_idx')],
                'unique_together': {('day', 'subscriber_code')},
            },
        ),
    ]
