# Generated by Django 6.0.4 on 2026-04-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delancert', '0004_telemetrychanneldailyagg_telemetryuserdailyagg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetryjobrun',
            name='job_type',
            field=models.CharField(choices=[('run', 'run'), ('sync', 'sync'), ('merge_ott', 'merge_ott'), ('integrity_check', 'integrity_check'), ('ml_build_dataset', 'ml_build_dataset'), ('ml_train', 'ml_train')], db_index=True, max_length=32),
        ),
    ]
