# Generated by Django 6.0.4 on 2026-04-28 13:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delancert', '0005_alter_telemetryjobrun_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetryjobrun',
            name='job_type',
            field=models.CharField(choices=[('run', 'run'), ('sync', 'sync'), ('merge_ott', 'merge_ott'), ('integrity_check', 'integrity_check'), ('ml_build_dataset', 'ml_build_dataset'), ('ml_train', 'ml_train'), ('ml_predict', 'ml_predict')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='TelemetryUserDailyPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('subscriber_code', models.CharField(db_index=True, max_length=50)),
                ('horizon_days', models.IntegerField(db_index=True, default=7)),
                ('y_pred_watch_seconds', models.FloatField()),
                ('model_dir', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'telemetry_user_daily_prediction',
                'indexes': [models.Index(fields=['day', 'horizon_days'], name='telemetry_u_day_d17986_idx'), models.Index(fields=['subscriber_code', 'day'], name='telemetry_u_subscri_6b1533_idx')],
                'unique_together': {('day', 'subscriber_code', 'horizon_days')},
            },
        ),
    ]
