# Generated by Django 6.0.4 on 2026-04-28 15:57

import django.core.serializers.json
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delancert', '0006_alter_telemetryjobrun_job_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryModelArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(db_index=True, max_length=64)),
                ('model_dir', models.CharField(max_length=500, unique=True)),
                ('feature_names', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('metrics', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'telemetry_model_artifact',
                'indexes': [models.Index(fields=['task', 'active', 'created_at'], name='telemetry_m_task_def4c2_idx')],
            },
        ),
    ]
