# Generated by Django 6.0.4 on 2026-04-28 20:15

import django.core.serializers.json
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delancert', '0008_alter_telemetryjobrun_job_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryAgentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('noc', 'noc'), ('analyst', 'analyst')], db_index=True, max_length=16)),
                ('severity', models.CharField(choices=[('info', 'info'), ('warning', 'warning'), ('critical', 'critical')], db_index=True, default='info', max_length=16)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('report_md', models.TextField()),
                ('ops_alerts', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('ops_summary', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('llm_enabled', models.BooleanField(default=False)),
                ('llm_model', models.CharField(blank=True, max_length=200, null=True)),
                ('llm_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'telemetry_agent_report',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report_type', 'created_at'], name='telemetry_a_report__5fc4c9_idx'), models.Index(fields=['severity', 'created_at'], name='telemetry_a_severit_643055_idx')],
            },
        ),
    ]
